### ISSUE TITLE
Black Screen when starting

### ISSUE THREAD

**Issue by Wuemeli** [gabsroot/cs2-python-cheat#1]
See title

**Comment by gabsroot** [comment]
Hi, as this cheat is external, CS2 needs to be in "Window Mode" to work. If you are experiencing a black screen when starting up, use the ALT + Enter shortcut to resolve it :)

**Comment by gabsroot** [comment]
> See title

hi, as this cheat is external, CS2 needs to be in "Window Mode" to work. If you are experiencing a black screen when starting up, use the ALT + Enter shortcut to resolve it :)
